@startuml Graphic
interface IGraphic{
  +Init():int_16t
  +Draw(Vec2 pos, HTEXTURE texture):int_16t
  +DrawReverse(Vec2 pos, HTEXTURE texture):int_16t
  +DrawRotate(Vec2 pos, HTEXTURE texture, Degree deg):int_16t
  +DrawExtend(Vec2 pos, HTEXTURE texture, Scale scale):int_16t
  +DrawMod(Vec2 pos, HTEXTURE texture, Degree deg, Scale scale):int_16t
  +SetRenderState():int_16t
  +SetTextureStage():int_16t
  +SetSamplerState():int_16t
  +Release():int_16t
}

class DirectXDevice{
  -m_pDirect3D:ComPtr<LPDIRECT3D>
}

class DirectXGraphicDevice{
  -m_pD3DDevice:ComPtr<LPDirect3DDevice>
}

class DirectX9{
  +Init():int_16t
  +Draw(Vec2 pos, HTEXTURE texture):int_16t
  +DrawReverse(Vec2 pos, HTEXTURE texture):int_16t
  +DrawRotate(Vec2 pos, HTEXTURE texture, Degree deg):int_16t
  +DrawExtend(Vec2 pos, HTEXTURE texture, Scale scale):int_16t
  +DrawMod(Vec2 pos, HTEXTURE texture, Degree deg, Scale scale):int_16t
  +Release():int_16t
  -m_D3Dpp:D3DPRESENT_PARAMETERS
}

class DirectX11{

}



class ColorRGB{
  +red:unsigned char
  +green:unsigned char
  +blue:unsigned char
}

IGraphic <|-- DirectX9
IGraphic <|-- DirectX11
DirectX9 *-- TextureManager

@enduml