@startuml Tau

set namespaceSeparator ::

namespace Tau{
  class Tau{
    -m_graphic:Graphic
    -m_sound:Sound
    -m_movie:Movie
    -m_input:Input

    {static} +Init():int16_t
    {static} +Release():int16_t
  }
}

Tau::Tau *-- Tau::Graphic
Tau::Tau *-- Tau::Sound
Tau::Tau *-- Tau::Movie
Tau::Tau *-- Tau::Input

@enduml
